version: '3.8'

services:
  # Service Backend (FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  # Service Frontend (Streamlit)
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
